* My build of Dmenu

  This is my build of dmenu, forked by the [[https://tools.suckless.org/dmenu][suckless guys]]. You can see the
  original README [[file:./README.orig][here]].

  The patches applied are located in [[./patches/]]. Unfortunately I do not
  remember the order of patching.

  This version of dmenu: 4.9
  
** My patches

   Inside the directory [[./my-patches/]] I will keep whatever patches I have
   defined for personal use.

*** Xresouces highlight colors
    
    File: [[./my-patches/xres-hl.diff/]]

    This patch adds Xresouces options to modify highliting
    colors. It should be applied after both the [[./patches/dmenu-highlight-4.9.diff/][highlight]] and the
    [[./patches/dmenu-xresources-4.9.diff/][xresources]] patches. 
    
    Four new options are provided:
     + =selbackground-hl=: The selected entry's highlighted background color.
     + =selforeground-hl=: The selected entry's highlighted text color.
     + =normbackground-hl=: The other entries' highlighted background
       color.
     + =normforeground-hl=: The other entries' highlighted text color.
